theme: minima
description: Research projects on visualization and user intent.
baseurl: "" # 如果是 GitHub Pages，保持为空
markdown: kramdown
plugins:
  - jekyll-seo-tag

# 引入自定义样式
include:
  - assets/css/style.css
